### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by f-mer** [rastapasta/node-pokemongo-protobuf#1]
Tried to compile with compile.pl and compile.sh without success.
Running ./compile.sh inside the script dir does not work: "compiled.proto: No such file or directory".

**Comment by kjvalencik** [comment]
Also, having difficulty figuring this out.

**Comment by rastapasta** [comment]
All changed during the iterations of POGOProtos, it's having its own compile script by now.
To use it: go to the POGOProtos sub-branch, execute **python compile_single.py** and copy the resulting out/POGOProtos.desc to the data/ folder.
TODO: adding this as a npm pre-publish hook
