### ISSUE TITLE
Will npm i --save pokemongo-protobuf clashes with package.json?

### ISSUE THREAD

**Issue by kmcheung12** [rastapasta/node-pokemongo-protobuf#5]
`npm i --save pokemongo-protobuf` and `package.json` both use `"pokemongo-protobuf"`
When I install with `npm i --save pokemongo-protobuf`, it says

> npm ERR! Refusing to install pokemongo-protobuf as a dependency of itself

When changing `package.json`'s `name` to something else, the install succeed.
I am not sure the cause of the error as I'm no node developer. Is it a problem that the name of the module is the same as package.json?

**Comment by rastapasta** [comment]
Hey @kmcheung12, this is not a stand-alone code - its meant to be used in other projects as layer between the protobuf definitions and other logic. a call to `npm i --save pokemongo-protobuf` is a shortcut of adding it manually to a project's package.json.

**Comment by kmcheung12** [comment]
@rastapasta  Thanks for the explanation!
